name: motherclub
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  infinite_scroll_pagination: ^3.1.0
  device_preview: ^0.7.4
  google_fonts: ^2.1.0
  connectivity: ^3.0.0
  cool_alert: ^1.1.0
  dotted_border: ^2.0.0+1
  flutter_toggle_tab: ^1.1.7
  expandable: ^5.0.1
  # Social Login
  google_sign_in: ^5.1.1
  firebase_auth: ^3.1.1
  flutter_login_facebook: ^1.2.0
  firebase_core: ^1.6.0
  provider: ^5.0.0
  http: ^0.13.3
  simple_gradient_text: ^1.2.2
  shimmer: ^2.0.0
  flutter_typeahead: ^3.2.1
  shared_preferences: ^2.0.4
  progress_state_button: ^1.0.3
  progress_indicators: ^1.0.0
  awesome_loader: ^0.0.3
  flutter_otp_text_field: ^1.0.0

  carousel_slider: ^4.0.0
  rxdart: ^0.27.3
  dio: ^4.0.4
  flutter_bloc: ^7.0.0
  image_picker: ^0.8.4+4
  image: ^3.0.8
  intl: "0.17.0"
  video_player: ^2.2.7
  flick_video_player: ^0.3.1
  flutter_paytabs_bridge:
#  flutter_launcher_icons:
  size_helper: ^0.0.1+1
  url_launcher: ^6.0.18
dev_dependencies:
  flutter_test:
    sdk: flutter
#
#flutter_icons:
#    android: true
#    ios: true
#    image_path: "assets/images/sort.png"

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icon/icon.png
    - assets/logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
